spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/webase?characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

    #配置监控统计拦截的filter,去掉后监控界面sql将无法统计,用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxAtive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache, 并且制定每个PSCache的大小
    poolPreparedStatements: true
    maxpoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties来打开mergeSql功能;慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
    minidle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
   # useGlobalDataSourceStat: true

  jpa:
    database: MySQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  #mvc:
  #  view:
  #    prefix: /WEB-INF/jsp/
   #   suffix: .jsp

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5